source 'http://rubygems.org'

gem 'rails', '3.1.1'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'uglifier', '>= 1.0.3'
  gem "therubyracer"
  gem "less-rails"
  gem 'twitter-bootstrap-rails'
end

# Authentication & Third Party APIs
gem 'devise', '1.5.2'
gem 'oauth', '0.4.5'
gem 'roauth', '0.0.7'
gem 'omniauth'
gem 'omniauth-twitter', '~> 0.0.16'
gem 'twitter', '4.5.0'

gem 'jquery-rails'

# Other
gem 'json', '1.8.0'
gem 'bson_ext'
gem 'prototype-rails', '3.1.0'
gem 'prototype_legacy_helper', '0.0.0', :github => 'rails/prototype_legacy_helper'


# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

group :test do
  # Testing
  gem 'rack-test', '0.6.2'
  gem 'shoulda', '3.0.1'
  gem 'shoulda-matchers', '1.0.0', :require => false
  gem 'cucumber-rails', '1.3.0', :require => false
  gem 'selenium-webdriver', '2.29.0'
  gem 'capybara-firebug', '1.3.0'
  gem 'poltergeist', :github => 'jonleighton/poltergeist', :ref => 'c3c51061'
  gem 'email_spec', '1.4.0'
  gem 'capybara', :github => 'jnicklas/capybara', :ref => '4842732e'
  gem 'xpath', :github => 'jnicklas/xpath', :ref => 'd72bd90c'

  # Other
  gem 'simplecov', :require => false
  gem 'nyan-cat-formatter', '0.3.0'
  gem 'fuubar'
  gem 'fuubar-cucumber'
end
